### PR TITLE
Alternative approach to column mapping

### PR DESCRIPTION
**Pull request by jmobrien**
So, looking back at #146, I realized the work I was doing was kind of a kluge, trying to build on the existing functionality that all felt really dated and that both I and others (e.g. #192) are working around to try and implement some good ideas.  So, I'm submitting this pretty complete revision to `read_survey()` that I think represents a big step forward.  This implements all the proposed functionality from #146 in, I think a much better way, along with addressing a few other things besides.  If used, this would make #146 obsolete and ignorable.

1. Column maps are now generated from the response data metadata, done cleanly and simply w/in `read_survey()`.  Now works with both the current and legacy format (FYI legacy is disappearing March 2021).
2. Generated column maps provide: 
       1. Attachable column map as data frame attribute. This is controlled by param `add_column_map`, default `TRUE`.
       2. Content for the `sjlabelled`-style label attributes. This is now controlled by new param `add_var_labels,` with default `TRUE`, addressing #134.  Label content was changed to include the entire variable description rather than the often-ambiguous subquestions, addressing #168.  The main/subquestion separation is still maintained in the column map, with a slightly cleaner implementation to generate that separation.
       3. QID-based names that also incorporate choice ID to preserve uniqueness (maintaining improvements provided by #182)
3. Simplified workflow now handles 0-response downloads the same as any other.  @lyh970817 was absolutely right to try to target the previous version's strange handling of 0-response situations in #192, but this just circumvents the issue entirely.
4. General restructuring to use "tidy" tools and create an organized workflow that should be easier to maintain.  
5. Includes the `extract_colmap()` function that outputs the column map attribute to be saved as its own object.
6. Tests added for examining the generated column maps extracted by `extract_colmap()`, implicitly testing `read_survey()` as well.

`read_survey()` is really the likely to represent the core of data processing that `qualtRics` does for most users, so hopefully this will be a useful change for everyone.  

Still maybe needs tests for `import_id = TRUE`, but that really seems like a minor revision for the current tests for `fetch_survey()`, and those depend on qualtrics surveys that aren't mine, so I thought I'd hold off on that.

### CODE REVIEW

**Comment by jmobrien** [comment]
One FYI - An API token of mine got pushed somehow to one of the commits in a fixture.  Still not sure quite what happened there; the token appeared properly masked on the local, which was supposedly up-to-date with the remote.  Regardless, that token has already been discarded, and the current version should be properly masked.

**Comment by jmobrien** [comment]
Made a few fixes to the documentation/imports/tests so that now all the checks pass.  Also see PR #200, which was a source for me of some problems with getting the tests to work appropriately.  

One other thing--I did take advantage of multi-column output from `mutate` ([here](https://github.com/ropensci/qualtRics/pull/199/files#diff-79bb8b511bf5267234e54ba785119e94739b76559aa1fb24e6b4c100f66e70d6R163-R167) and [here](https://github.com/ropensci/qualtRics/pull/199/files#diff-79bb8b511bf5267234e54ba785119e94739b76559aa1fb24e6b4c100f66e70d6R191-R202)), which means that this relies on dplyr >= 1.0.  That could be changed, but the code's a lot simpler this way.

**Comment by jmobrien** [comment]
Okay, just for thoroughness I'm going to use bfg to remove my url and (expired) token.  Converting this to draft while I get that done.

**Comment by jmobrien** [comment]
Didn't remove things but there's really nothing there that's actually sensitive, so this is ready for review whenever.

**Comment by juliasilge** [comment]
Thank you so much for all this thoughtful work @jmobrien! 🥳  

It looks really fantastic and solves a significant challenge so many users have been having. I added a bit to the docs for `extract_colmap()` for folks to see how to use it; it worked really well on all the surveys I tried it out with.

**Pull request merged**
