### PR TITLE
New fetch_mailinglist (since now bind_rows takes NULLs)

### PR DESCRIPTION
**Pull request by jmobrien**
Alternative to #305.  With the NULL issues discussed in #212 gone, we have an option to both simplify the code while also fixing the same issues addressed by #304.

This version is more straightforward than the array of `purrr::map`s, and doesn't need the sort of patching they require in #305.  One downside is the code is less explicit about the intended output than before (but there might be a better approach in this vein).

Possibly useful for new upcoming functions `list_mailinglist` and kin.

### CODE REVIEW

**Comment by juliasilge** [comment]
I think this option looks quite nice, and like you say, this approach will be extensible. Was it passing the tests locally for you? It seems like we are seeing this error (again?):

> Please use an explicit call to `as.character()` within `map_chr()` instead.

**Comment by jmobrien** [comment]
There are a couple of new functions from purrr/dplyr/tidyr that got introduced here and need to be added to the  roxygen & genereated docs.  Hopefully that will take care of things.

**Review by juliasilge — APPROVED** [review]
This is looking great! 🙌

**Comment by juliasilge** [comment]
Yes @pschatz25 for now, you'll need to install from GitHub via `remotes::install_github("ropensci/qualtRics")`.

**Comment by pschatz25** [comment]
Got it. Now I'm back up and running. Thanks, @juliasilge!

**Pull request merged**
