### PR TITLE
using jsonlite to automatically build payloads

### PR DESCRIPTION
**Pull request by jmobrien**
Suggested change--still needs tests written, but thought I'd go ahead and put it in the pipe for review.  So far seems to work fine.

- Uses `toJSON` from package `jsonlite` for automated construction of payloads, eliminating the massive manual build using a bunch of `ifelse`s and `paste`.  `qualtRics` has imported functions from `jsonlite` for quite a while now, so this doesn't add any new dependencies.  

- `purrr::discard` drops any null parameters when building, as qualtrics API doesn't like actual json `nulls` or empty sets.

- Retains original technique for formatting`start_date` and `end_date` to fit ISO 8601 as expected (https://github.com/ropensci/qualtRics/compar/master...jmobrien:payload?expand=1).  Looking ahead, though, could be easier now to set up more flexible handling of start and end times, useful now that since-last-response request functionality is gone, see #153.

### CODE REVIEW

**Comment by juliasilge** [comment]
This is fantastic @jmobrien! Thank you so much. 💯

**Comment by jmobrien** [comment]
Glad it helped.  Looking forward, we might want to think about how best to have this tool accept the standard date/time output used by the `readr` tools we're currently employing in `read_survey`.  I played around with it for a bit earlier before submitting but didn't see a standard tool that could do date+time with the `"T"` separator, plus I wasn't sure how to implement timezones in a way that made the most sense and properly considered how the `useLocal` flag was set.

**Comment by juliasilge** [comment]
If you want to open an issue with your ideas and any summary of what you tried, we can save that for later.

**Comment by jmobrien** [comment]
Can't say I spent a ton of time on it, but I'll write a few lines.

**Pull request merged**
